FROM ubuntu:20.04
RUN sudo apt-get install python3 
RUN sudo apt-get install python-pip3
RUN pip install git+git://github.com/tenable/pytenable.git#egg=pytenable
RUN apt-get install -y strace ltrace curl wget gcc netcat vim gdb git make
RUN pip install -U Flask
RUN pip install requests
RUN pip install urllib3
pip install psutil

WORKDIR /scripts
VOLUME /scripts
